version: "2"
services:
  webscrap:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo 
    environment:
      - PORT=8080
      - MONGO_URL=mongodb://mongo:27017/webscrap
  mongo:
    image: mongo